[params]
  fullName = "Full Name"

  [[params.navItems]]
    title = "Home"
    path = "/"

  [[params.navItems]]
    title = "Articles"
    path = "/post"

  [[params.navItems]]
    title = "Projects"
    path = "/project"
