name = "Personal Website Theme"
license = "MIT"
licenselink = "https://github.com/habenamare/custom-hugo-theme/blob/master/LICENSE"
description = ""
homepage = "http://example.com/"
tags = ["blog"]
features = []
min_version = "0.62.2"

[author]
  name = "Haben Amare"
  homepage = "habenamare.com"
